### ISSUE TITLE
2.0: New UI via Endless Browser (was: tabbed browsing / firefox-ios UI?)

### ISSUE THREAD

**Issue by mtigas** [mtigas/OnionBrowser#13]
Updated 2016-08-18: Progress is being made on a "tabbed browsing" interface, via totally-rewritten version of Onion Browser, based on https://github.com/jcs/endless Leaving this ticket open as a meta-ticket until that gets closer to release (and we get some public commits and some issues specific to the implementation).

**Comment by fbender** [comment]
Would it be a good idea to re-implement the current Tor functionality into a fork of [mozilla/firefox-ios](https://github.com/mozilla/firefox-ios) or [brave/browser-ios](https://github.com/brave/browser-ios) (which itself builds upon firefox-ios)? That would free you from caring about building a browser and just focus on the Tor functionality (so rather similar to what the TorBrowser project does).

**Comment by mtigas** [comment]
@fbender Both Firefox and Brave appear to use the newer WKWebView API, which in #47 we realized completely disallows us from using `NSURLProtocol` to intercept HTTP requests and route them through our Tor process.

That said, I'm actually working on a totally-rewritten Onion Browser 2.0 that is essentially a fork of https://github.com/jcs/endless for the exact reasons you mention. Lemme update this ticket to reflect that.

**Comment by fbender** [comment]
Good to know. But how does Google do it with their Chrome Browser? They are using their own network stack and should be using WKWebView as well. Maybe they reimplemented everything on top of raw TCP streams? That should be somewhere in the Chromium source code I presume …

**Comment by mtigas** [comment]
A few folks and I actually thought about that. Looks like they *were* implementing their own network stack (which is how they had their Data Saver compression proxy and other neat things) in Chrome iOS, but at some point they updated to use WKWebView and stopped doing this.

https://support.google.com/chrome/answer/6323113

> Features not available on iPhone and iPad
> Some of your Chrome features and settings will not be available at this time because of iOS constraints. Downloads that require authentication might not work, and the following features and settings had to be removed:
> 
> Data Saver
> Cookie settings
> Auto-Detect Encoding
> Do Not Track setting
> Enterprise support and multi-profiles
> If Apple makes changes to WKWebView to allow these features, we will add them back in.

We interpret this this to mean that they ran into the same limitation with the new API and actually had to stop using their own network stack. So, super interesting.

**Comment by chrisballinger** [comment]
I've had a radar open for this since April 15, 2015: http://www.openradar.me/radar?id=5547938658910208

No response from Apple.

**Comment by tladesignz** [comment]
Since Onion Browser 2 is now released, I close this issue. Feel free to reopen, if I missed something.
