### ISSUE TITLE
2.0: Use Tor.framework to decouple Tor build/run

### ISSUE THREAD

**Issue by chrisballinger** [mtigas/OnionBrowser#45]
(_was "Decouple Tor management from AppDelegate"_ -mtigas)

It would be tremendously useful for other developers in this space if we could agree on a standard implementation for Tor on iOS that can be bundled more easily. I originally created [OnionKit](https://github.com/chatsecure/onionkit) as a way to "library-ify" your Tor management code, but I'm not particularly happy with it and your socket-based solution might be better than Tor.framework's approach from a maintainability perspective.

The main changes that need to be made are removing the references to AppDelegate.h from TorController and TorWrapper so other projects can include this code without breaking their own apps. Down the road, moving the management code to a separate repo and shipping it as a library (or even better, a Cocoapod) would make it a lot easier for all of us to collectively maintain.

**Comment by mtigas** [comment]
Update on this: I've got some work in progress that's a fork of https://github.com/jcs/endless that's actually using https://github.com/iCepa/Tor.framework for this. Things are looking kind of good so far, hopefully I'll have a new public branch up soon.
