### ISSUE TITLE
http://ip-check.info

### ISSUE THREAD

**Issue by hdatma** [mtigas/OnionBrowser#66]
The above site crashes the browser systematically. 

**Added info**
... when blocking all active content (no crash when blocking Ajax/Media/WebSockets only).

**Comment by JRock007** [comment]
Thanks a lot for your feedback!
I just tested this website, and haven't been able to reproduce this bug on my testing devices. Which iOS version are you using?

**Comment by tladesignz** [comment]
Not anymore with version 2. Closing.
