### ISSUE TITLE
Cloudflare recaptcha fails with OnionBrowser making many sites unusable

### ISSUE THREAD

**Issue by msc-** [mtigas/OnionBrowser#69]
When using Tor, a large number of sites, that are fronted by Cloudflare, force you to do an "I am not a robot" test depending on the Tor exit node you are using. These fail every time in OnionBrowser but work fine in TorBrowser on multiple platforms. Therefore the problem appears to be with OB. Here is what happens:

A page from Cloudflare appears saying a test is required to complete the connection with a single check box labelled "I am not a robot" near the center of it. Click this and a test appears, usually a grid of pictures from which you have to pick all those with street signs, rivers or something, with a `Verify` button at the bottom. Check the appropriate images then click the verify button. In pretty short order a message box appears saying something like "Couldn't connect to recaptcha at google.com". This happens every time you click the verify button making it impossible to proceed to the web page.

github.com is one of the sites for which this happens.

**Comment by daxelrod** [comment]
You can work around this by going to Browser Settings and changing the "Active Content Blocking" setting from the default "Block Ajax/Media/WebSockets" to "Block All Active Content".

If you have JavaScript turned on, you get served a version of the ReCaptcha that appears to require Ajax to work correctly, which won't work if "Block Ajax/Media/WebSockets" is set.

However, with JavaScript completely turned off, you are served a ReCaptcha that does not require JavaScript, and you should be able to complete it.

**Comment by MarkCallow** [comment]
This is a not very appealing workaround. Some sites are hopeless without JavaScript.

**Comment by MarkCallow** [comment]
I just noticed you closed this. Why do you not plan to fix i? Put another way, why is Ajax lumped with media & web sockets for disablement?

**Comment by tladesignz** [comment]
Just stumbled over this in my old marked emails list. 
Sorry, it was a tough year for OnionBrowser, but now we're back to it.
There's a related issue: #120
There's no fix for Recaptcha, actually it should just work. 
Anyway we're going to release 2.2.0 soon, which improves a lot of things. (Better Tor, e.g.)
