### ISSUE TITLE
Singnal SIGPIPE break point, when debug executable

### ISSUE THREAD

**Issue by Tuzr** [mtigas/OnionBrowser#71]
When I debug the executable at Xcode , 
It will show break point like the pic below:
![2016-06-03 5 29 21](https://cloud.githubusercontent.com/assets/6936130/15775112/bbe271ea-29b2-11e6-8727-74349dd4707f.png)
And it will keep break, even step out.
Is that something wrong or it just working normally?
Thanks !

**Comment by tladesignz** [comment]
This is an issue with the Xcode debugger. It will just always catch SIGPIPEs. If you disconnect the debugger, code in the App can handle these instead.
