### ISSUE TITLE
Issue when running build

### ISSUE THREAD

**Issue by allurewebsolutions** [mtigas/OnionBrowser#75]
After cloning, I run ./build.sh and get the following error:

Downloading openssl-1.0.2h.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) Unknown SSL protocol error in connection to www.openssl.org:443

**Comment by mtigas** [comment]
@allurewebsolutions 
What OS are you using? What version of curl is on your system (full output of `curl --version`)?

The OpenSSL site is HTTPS-only now and it [looks like](https://www.ssllabs.com/ssltest/analyze.html?d=www.openssl.org&s=194.97.150.234&hideResults=on) the SSL configuration of that site only supports TLS 1.1 and TLS 1.2, and some older tools (including anything linked against OpenSSL 0.9.X) may not support connections to their server.

**Comment by mikedoubintchik** [comment]
I'm on OSX 10.11.6 using curl 7.43.0

[image: photo]

**Comment by mtigas** [comment]
That’s very odd. I'm on the same OSX version and same curl, and don’t seem to be having that issue.

```bash
$ curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 
$ which curl
/usr/bin/curl
$ curl -vv -O https://www.openssl.org/source/openssl-1.0.2h.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 194.97.150.234...
* Connected to www.openssl.org (194.97.150.234) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.openssl.org
* Server certificate: GlobalSign Domain Validation CA - SHA256 - G2
* Server certificate: GlobalSign Root CA
> GET /source/openssl-1.0.2h.tar.gz HTTP/1.1
> Host: www.openssl.org
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 08 Aug 2016 19:03:13 GMT
< Server: Apache/2.4.7 (Ubuntu)
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Last-Modified: Tue, 03 May 2016 13:57:13 GMT
< ETag: "507b2c-531f07c730313"
< Accept-Ranges: bytes
< Content-Length: 5274412
< Content-Type: application/x-gzip
< 
  0 5150k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{ [16384 bytes data]
100 5150k  100 5150k    0     0  2855k      0  0:00:01  0:00:01 --:--:-- 2855k
* Connection #0 to host www.openssl.org left intact
```

Especially curious since `SecureTransport` in the version line means that curl is using the OSX crypto stack, not an OpenSSL or anything like that. So you and I _should_ be having the same result here.

Can you try to download manually via `curl -vv -O https://www.openssl.org/source/openssl-1.0.2h.tar.gz` and provide the full output of that here?

**Comment by mikedoubintchik** [comment]
➜  Downloads curl -vv -O
https://www.openssl.org/source/openssl-1.0.2h.tar.gz
-   Trying 194.97.150.234...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
  Current
                                 Dload  Upload   Total   Spent    Left
  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0\* Connected to www.openssl.org (194.97.150.234) port 443 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0\* Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
- TLSv1.0 (OUT), TLS handshake, Client hello (1):
  } [95 bytes data]
- Unknown SSL protocol error in connection to www.openssl.org:443
- Closing connection 0
  curl: (35) Unknown SSL protocol error in connection to www.openssl.org:443

[image: photo]

**Comment by mtigas** [comment]
Ah, looks similar to https://github.com/Homebrew/legacy-homebrew/issues/47546

Do you have another version of openssl that's maybe taking precedence? (What's the output of `which openssl`?)

According to that issue, you might need to update the Xcode Command Line Tools. Maybe.
* If you have Xcode, I'd just open the App Store and make sure that's up to date. Then ensure that you've opened the Xcode app at least once (to agree to terms of use and etc) then run `sudo xcode-select --install` in a terminal to ensure you've got the command-line tools configured.
* (If your Xcode is older or isn't installed via the Mac App Store, I’d probably uninstall that and reinstall it via the App Store.)
* Alternatively, you can try to manually download the updated Command Line Tools by [logging into the Apple Developer site](https://developer.apple.com/) and _then_ [going to this Downloads page](https://developer.apple.com/download/more/) and searching for the correct OSX & Xcode version (you probably want "Command Line Tools (OS X 10.11) for Xcode 7.3.1"). But to build Onion Browser, you do need the full Xcode anyway.

**Comment by mikedoubintchik** [comment]
I'm using: /usr/bin/openssl

According to the App Store I have xcode 7.3.1 and I've been using it quite
frequently lately.
